export { EmployeesIllustration } from './EmployeesIllustration'
export { DepartmentsIllustration } from './DepartmentsIllustration'
export { HolidaysIllustration } from './HolidaysIllustration'
export { ExpensesIllustration } from './ExpensesIllustration'
export { AttendanceIllustration } from './AttendanceIllustration'
export { SalaryIllustration } from './SalaryIllustration'
export { SalaryAdjustmentIllustration } from './SalaryAdjustmentIllustration'
export { NotificationsIllustration } from './NotificationsIllustration'
